export const SET_CATEGORIES = 'SET_CATEGORIES';
export const STORE_NEW_ORDER_IS_SUCCESS = 'STORE_NEW_ORDER_IS_SUCCESS';

export const SHOW_FORM = 'SHOW_FORM';
export const MOUNT_CATEGORY_TO_UPDATE = 'MOUNT_CATEGORY_TO_UPDATE';
export const HIDE_FORM = 'HIDE_FORM';
export const FORM_IS_LOADING = 'FORM_IS_LOADING';

export const ADD_MAIN_CATEGORY = 'ADD_MAIN_CATEGORY';
export const STORE_IS_SUCCESS = 'STORE_IS_SUCCESS';
export const STORE_CATEGORY_ERROR = 'SET_STORE_CATEGORY_ERROR';

export const UPDATE_MAIN_CATEGORY = 'UPDATE_MAIN_CATEGORY';
export const UPDATE_IS_SUCCESS = 'UPDATE_IS_SUCCESS';
export const UPDATE_CATEGORY_ERROR = 'SET_UPDATE_CATEGORY_ERROR';

export const CONFIRM_CATEGORY_TO_DELETE = 'CONFIRM_CATEGORY_TO_DELETE';
export const CANCEL_CETAGORY_DELETE = 'CANCEL_CETAGORY_DELETE';
export const REMOVE_MAIN_CATEGORY = 'REMOVE_MAIN_CATEGORY';
export const DELETE_IS_FINISHED = 'DELETE_IS_FINISHED';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';
