export const MOUNT_DATA = 'MOUNT_DATA';
export const FORM_NEW_INVOICE_OPENED = 'FORM_NEW_INVOICE_OPENED';
export const INVOICE_STORE_LOADING = 'INVOICE_STORE_LOADING';
export const INVOICE_STORE_ERROR = 'INVOICE_STORE_ERROR';
export const INVOICE_STORE_SUCCESS = 'INVOICE_STORE_SUCCESS';
export const ADD_NEW_INVOICE = 'ADD_NEW_INVOICE';
export const LOADING_DATA = 'LOADING_DATA';

// ACTIONS FOR SHOW INVOICE CARD
export const SELECTED_INVOICE_OPENED = 'SELECTED_INVOICE_OPENED';
export const SELECTED_INVOICE_LOADING = 'SELECTED_INVOICE_LOADING';
export const SELECTED_INVOICE_ERROR = 'SELECTED_INVOICE_ERROR';
export const MOUNT_SELECTED_INVOICE = 'MOUNT_SELECTED_INVOICE';
export const UNMOUNT_SELECTED_INVOICE = 'UNMOUNT_SELECTED_INVOICE';

export const PAYMENT_FORM_OPENED = 'PAYMENT_FORM_OPENED';
export const PAYMENT_STORE_LOADING = 'PAYMENT_STORE_LOADING';
export const PAYMENT_STORE_SUCCESS = 'PAYMENT_STORE_SUCCESS';
export const PAYMENT_STORE_ERROR = 'PAYMENT_STORE_ERROR';
export const ADD_PAYMENT_TO_INVOICE = 'ADD_PAYMENT_TO_INVOICE';
