export const MOUNT_DATA = 'MOUNT_DATA';
export const FORM_NEW_INVOICE_OPENED = 'FORM_NEW_INVOICE_OPENED';
export const INVOICE_STORE_LOADING = 'INVOICE_STORE_LOADING';
export const INVOICE_STORE_ERROR = 'INVOICE_STORE_ERROR';
export const INVOICE_STORE_SUCCESS = 'INVOICE_STORE_SUCCESS';
export const ADD_NEW_INVOICE = 'ADD_NEW_INVOICE';
export const MOUNT_SELECTED_INVOICE = 'MOUNT_SELECTED_INVOICE';
export const LOADING_DATA = 'LOADING_DATA';
